import { Button, useMantineTheme } from '@mantine/core';
import Head from 'next/head';

export default function Home() {
  const theme = useMantineTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button fullWidth color={theme.primaryColor}>
          Hello
        </Button>
      </main>
    </>
  );
}
